config/routes.rb
Rails.application.routes.draw do

  root to: 'lists#index'
  resources :lists do 
    resources :items
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :list
end

app/models/list.rb
class List < ActiveRecord::Base
	has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = list.items.build
  end 

  # GET /items/1/edit
  def edit
    item
  end

  # POST /items
  # POST /items.json
  def create
    @item = list.items.build(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to list_path @list }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end



  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if item.update(item_params)
        format.html { redirect_to list_path(@list)}
        format.json { render :show, status: :ok, location: items_url }
      else
        format.html { render :edit }
        format.json { render json: item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    item.destroy
    respond_to do |format|
      format.html { redirect_to @list}
      format.json { head :no_content }
    end
  end

  def complete
    respond_to do |format|
      format.html { redirect_to @list}
    end
  end

  private

  def list
    @list ||= List.find(params[:list_id])
  end
  
  def item
    @item ||= list.items.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white item through.
  def item_params
    params.require(:item).permit(:task, :description, :completed, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to lists_url }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end



  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to lists_url}
        format.json { render :show, status: :ok, location: lists_url }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
  @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url}
      format.json { head :no_content }
    end
  end

  def complete
      respond_to do |format|
        format.html { redirect_to lists_url}
  end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/items/_form.html.erb
<%= form_for [@list, @item] do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="names">
    <%= f.label :task %><br>
    <%= f.text_field :task %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit "Update Item"%>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Back', list_path(@list) %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>
<h1>All Items</h1>

<table>
<h3>task Description</h3>
  <tbody>
    <% @items.each do |item| %>
      <tr>
      	<% if item.completed? %>
          <td><strike><%= item.task %><strike></td>
          <td><strike><%= item.description %><strike></td>
          <td><%= link_to 'Mark as incomplete', list_path(item, item: { completed: "0" }), method: :put %></td>
          <% else %>
          <td><%= item.task %></td>
          <td><%= item.description %></td>
          <td><%= link_to 'Mark as complete', list_path(item, item: { completed: "1" }), method: :put %></td>
          <% end %>
          <td><%= link_to 'Edit', edit_list_item_path(item, item.list.id) %></td>
          <td><%= link_to 'Delete', list_item_path(:id, :list_id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
  </tbody>
</table>

<br>


<%= link_to 'New task', new_list_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', @list %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>


<table>
<h3>
Task Name
</h3>
  <tbody>
  </tbody>
</table>

<br>
<%= link_to 'New Task', new_item_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewTodo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit "Create List"%>
  </div>
<% end %>

app/views/lists/_item.html.erb
      <tr>
      	<% if item.completed? %>
          <td><strike><%= item.task %><strike></td>
          <td><strike><%= item.description %><strike></td>
          <td><%= link_to 'Mark as incomplete', list_path(item, item: { completed: "0" }), method: :put %></td>
        <% else %>
          <td><%= item.task %></td>
          <td><%= item.description %></td>
          <td><%= link_to 'Mark as complete', list_path(item, item: { completed: "1" }), method: :put %></td>
          <% end %>
          <td><%= link_to 'Edit', edit_list_item_path(@list) %></td>
          <td><%= link_to 'Delete', list_item_path(:id, :list_id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>

app/views/lists/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>
<h1>All Todo Lists</h1>

<table>
<h3>
List Name
</h3>
  <tbody>
    <% @lists.each do |list| %>
      <tr>
          <td><%= link_to list.name, list %></td>
          <td><%= link_to 'Edit', edit_list_path(list) %></td>
          <td><%= link_to 'Delete', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>
<h1>All Items</h1>

<table>
<h3>Task Description</h3>
  <tbody>
    <% @list.items.each do |item| %>
      <tr>
        <% if item.completed? %>
          <td><strike><%= item.task %><strike></td>
          <td><strike><%= item.description %><strike></td>
          <td><%= link_to 'Mark as incomplete', list_item_path(@list, item, item: { completed: "0" }), method: :put %></td>
        <% else %>
          <td><%= item.task %></td>
          <td><%= item.description %></td>
          <td><%= link_to 'Mark as complete', list_item_path(@list, item, item: { completed: "1" }), method: :put %></td>
          <% end %>
          <td><%= link_to 'Edit', edit_list_item_path(@list, item) %></td>
          <td><%= link_to 'Delete', list_item_path(@list,item), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Task', new_list_item_path(@list) %>

<br>
<%= link_to "Back To All Lists", lists_path %>